const CodiFeedData = [
    { id: '1',
      title: 'First Item',
      src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '2',
      title: 'Second Item',
      src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '3',
      title: 'Third Item',
      src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '4',
      title: 'Third Item',
      src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '5',
      title: 'Third Item',
      src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '6',
      title: 'Third Item',
      src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '7',
      title: 'Third Item',
      src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '8',
    title: 'Third Item',
    src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '9',
    title: 'Third Item',
    src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '10',
    title: 'Third Item',
    src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '11',
    title: 'Third Item',
    src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '12',
    title: 'Third Item',
    src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '13',
    title: 'Third Item',
    src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '14',
    title: 'Third Item',
    src: require('../../android/app/src/assets/fonts/예일.png'),
    },
    { id: '15',
    title: 'Third Item',
    src: require('../../android/app/src/assets/fonts/예일.png'),
    },
  
  ];
  
  export default CodiFeedData;